### ISSUE TITLE
2.10.0 Updates

### ISSUE THREAD

**Issue by marksou** [TykTechnologies/tyk-docs-hugo#1153]

**Comment by marksou** [comment]
- [ ] Additional hook for plugin middleware to modify Response - [#1526](https://github.com/TykTechnologies/tyk/issues/1526) - @matiasinsaurralde 

- [x] Gateway Debug mode - [#168](https://github.com/TykTechnologies/product/issues/168) @adelowo 

- [ ] global response header transform middleware - [#2453](https://github.com/TykTechnologies/tyk/issues/2453) - @furkansenharputlu

- [ ] Added Admin APIs for Org Keys - [#1674](https://github.com/TykTechnologies/tyk-analytics/pull/1674) - @komalsukhani 

- [x] Enhanced Global Health Check API - @adelowo 

- [ ] Co-Process Response Plugins - @matiasinsaurralde 

- [x] Policy / Keys UX - @marksou 

- [x] Analytics update - @marksou 

- [x] Enhanced Detailed Logging - @adelowo 

- [x] ID Broker in Dashboard - @sredxny 

- [ ] Better Redis Failover - @gernest 

- [x] Weight Based Load Balancing - @buger 

- [x] Shard Ananlytics to different Data Sinks - @tbuchaillot 

- [ ] 404 Error Logging - @furkansenharputlu 

- [x] KV Store for Secrets - @adelowo 

- [x] New UI Screenshots - @marksou

**Comment by sredxny** [comment]
Documentation for TIB in: https://github.com/TykTechnologies/tyk-docs/issues/1225

**Comment by tbuchaillot** [comment]
Doc for  Shard **Ananlytics to different Data Sinks** :https://github.com/TykTechnologies/tyk-docs/issues/1228

**Comment by buger** [comment]
Debug mode https://github.com/TykTechnologies/tyk-docs/pull/1235/files

**Comment by buger** [comment]
Health Check API https://github.com/TykTechnologies/tyk-docs/pull/1236

**Comment by adelowo** [comment]
KV store for secrets https://github.com/TykTechnologies/tyk-docs/pull/1002

**Comment by buger** [comment]
Added docs on weighting https://github.com/TykTechnologies/tyk-docs/issues/1227
