### ISSUE TITLE
Release 2.8 leftovers

### ISSUE THREAD

**Issue by buger** [TykTechnologies/tyk-docs-hugo#759]
Release notes draft https://github.com/TykTechnologies/tyk/releases/tag/untagged-d76c36c66ae8c8f5ba65

- [x] Dynamic portal customization part can go straight to this page https://tyk.io/docs/tyk-developer-portal/customise/customise-with-templates/
- [ ] Extend policy documents with "Separate rate limits and quotas per API within same Policy", including Policy API https://github.com/TykTechnologies/tyk/issues/356 @dencoded 
- [ ] Add new page for API debugger (or section inside existing page) with screenshots. https://github.com/TykTechnologies/tyk-analytics-ui/issues/894 @buger 
- [ ] Add looping paragraph to URL rewriter section. And later separate page about more advanced usage, like SOAP support. May require a screenshot. https://github.com/TykTechnologies/product/issues/86 @buger 
- [ ] (Needs Release Note) Extend docs for Pump about new "hybird" pump, and in Hybrid docs, put note about possible configuration. https://github.com/TykTechnologies/tyk-pump/issues/80 @dencoded 
- [x] Add note about new `health_check_endpoint_name` Gateway config field https://github.com/TykTechnologies/tyk/issues/1981 @buger 
- [x] Update examples of using bundler CLI tools from to use `tyk bundler` instead of `tyk-cli bundler` https://github.com/TykTechnologies/tyk/issues/1492 @matiasinsaurralde 
- [ ] (Needs Release Note) Multi-org/multi-team support for enterprise https://github.com/TykTechnologies/product/issues/96 @joshblakeley 
- [x] Allow whitelist of acceptable ciphers https://github.com/TykTechnologies/tyk-analytics/issues/846 @asoorm 
- [x] Retrieve API details via public ID https://github.com/TykTechnologies/tyk-analytics/issues/1083 @adelowo 
- [x] Audit log improvements https://github.com/TykTechnologies/tyk-analytics/issues/344 @dencoded 
- [x] Request throttling https://github.com/TykTechnologies/tyk/issues/2089 @furkansenharputlu 
- [ ] Allow updating key by its hash https://github.com/TykTechnologies/tyk/issues/2055 @buger 
- [ ] (Needs Release Note) Proxy insecure skip verify support on per-api level https://github.com/TykTechnologies/tyk/issues/1837 @asoorm 
- [ ] Allow reset API quota for developers https://github.com/TykTechnologies/tyk-analytics/issues/1016 @buger 
- [ ] (PR) Password policy improvements https://github.com/TykTechnologies/tyk-analytics/issues/1012 @joshblakeley 
- [ ] Portal oAuth improvements @dencoded @lghiur 
- [ ] Creating developer subscription from developer screen

**Comment by matiasinsaurralde** [comment]
Docs that referenced `tyk-cli` were updated earlier this week: #755 👍
